### ISSUE TITLE
whilelist file 

### ISSUE THREAD

**Issue by ducna96** [Achiefs/fim#109]
hey, do you have any option to whilelist .ext file from path ?
example: 
 -path: /home/test/.*php

I just see ignore option, but option whilelist path seem not work.
thanks.

**Comment by okynos** [comment]
Hello @ducna96,

We will be glad to include this option as soon as possible. Meanwhile a good way to filter the events could be to use the indexer software to extract the set of events you need.

I will include this issue in the current roadmap, thanks!

**Comment by okynos** [comment]
Hello @ducna96,

We have developed this solution as an allow-list https://github.com/Achiefs/fim/pull/110 check if it matches your requirements. Meanwhile, we will code a way to support wildcards.

Thanks for your support!

**Comment by okynos** [comment]
We just published v0.4.6 with this issue solved. We will close this issue, don't hesitate to reopen it if you have any question or comments. Thanks!
