### ISSUE TITLE
Splunk Integration procedure

### ISSUE THREAD

**Issue by rpmranjith** [Achiefs/fim#119]
Hello Team,
We are planning to use this tool for our Linux environment, below are our requirements

Our Linux Servers: RHEL 8 & 9
SIEM Tool : Splunk 9.x

Kindly provide the exact package details for linux installation as well the procedure for Splunk Integration.

**Comment by okynos** [comment]
Hello @rpmranjith,

Take a look at our guide to install FIM in CentOS/RHEL based systems https://documentation.achiefs.com/docs/installation-guide.html#centos-based-install

On the other hand FIM hasn't native Splunk integration. Let me prepare some steps to integrate in a good manner.
Thanks for your feedback!

**Comment by rpmranjith** [comment]
hello @okynos 

Thanks for the quick reply on this, on the installation page I couldn't see the Linux support matrix, could you please confirm if this does this support both RHEL 8 & 9

**Comment by okynos** [comment]
Hi again @rpmranjith,

Thanks for your patience. I have set up a specific environment to launch some tests in RHEL 8 and 9.
Both systems work as expected.
Tests performed: 
- Installation.
- Run without errors.
- Event detection.
- Event reporting.

**Comment by rpmranjith** [comment]
Hello @okynos, 

Thanks for getting this checked out for RHEL 8 & RHEL 9, please do let us know once you have obtained some steps to integrate into Splunk

**Comment by okynos** [comment]
We will publish 0.4.8 in a few hours stay tuned!

**Comment by okynos** [comment]
Hello @rpmranjith,

We just published FIM v0.4.8 with Splunk integration support.
Take a look and let us know if it looks good to you.
https://github.com/Achiefs/fim/releases/tag/v0.4.8

The way to configure Splunk is to set an HTTP event collector in the Splunk indexer web. Then set the collector address and token into FIM configuration like this example https://github.com/Achiefs/fim/blob/main/test/unit/config/common/test_send_splunk.yml
Remember the port of the HTTP event collector is `8088`

**Comment by rpmranjith** [comment]
Hello @okynos thanks for getting this work done, we will test it out and keep you posted the status.

**Comment by okynos** [comment]
Hi @rpmranjith,

Yes, it works with Audit data. I want to mention some details to take into account:
- Create the HTTP event collector in Splunk's `data input` settings.
- Create an index called `fim_events` to store received events.
- Remember to set up the `https` URL with port `8088` in the address field inside the FIM configuration file.

Here you can see an example of Audit data inside Splunk indexer:
![image](https://github.com/Achiefs/fim/assets/10661307/abaed57d-5eb2-487a-9abc-59e67cd69b75)

My testing example configuration:
![image](https://github.com/Achiefs/fim/assets/10661307/7f0d3d04-8198-44d2-93f3-00eea35107be)

My Splunk configuration:
![image](https://github.com/Achiefs/fim/assets/10661307/53b8ba44-6110-4b5c-8e6c-5c1ba162f359)

I am working in this documentation issue to make it clear https://github.com/Achiefs/documentation.achiefs.github.io/issues/5

**Comment by rpmranjith** [comment]
Hello @okynos 

Thanks for your help I have installed on tested on one of our Linux system it works as expected, and able to forward the logs to Splunk and see the logs as needed

just couple of clarifications 
1. is there any log rotation can be done through tool itself
2. If no log rotation available shall we use of our own log rotation mechanicam to rotate the logs.
3. Is there any enterprise configuration to do FIM which you recommend please?

**Comment by okynos** [comment]
Hello @rpmranjith,

I'm glad to hear that it works as expected. To the clarifications part:
1. Currently, FIM doesn't auto-rotate the `events.json` log. I will create a new issue to include it. You don't need to store events in the `events.json` file If you sent the events to Splunk directly. You could set up the `destination` parameter to `network`. It will send events only to Splunk or Elastic and not to the file. More information https://documentation.achiefs.com/docs/configuration-file.html#destination
2. You could use native Linux tools like `logrotate`. Try to rotate the log on low system events load. It will avoid the rotation method to chomp events.
3. Could you include additional details about enterprise configuration? I mean. Do you want to tweak the hash processing size, the max events load or the queue? Take a look at https://documentation.achiefs.com/docs/configuration-file.html, where there is a description of each parameter available. There is a new parameter called `max_file_checksum` inside the events section. It defines the maximum size of the checksum to hash. I will add it to the documentation soon.
4. Let me know if you want to include new parameters in the configuration or improve some features. I will add them as soon as possible.

Thanks for your feedback. I really appreciate it.

**Comment by rpmranjith** [comment]
hello @okynos, 

could you please help me on this, though we have updated "ignore" parameter in the configuration file, still it capturing in the events, hence I have just prefixed * below the .swp, please advise  

![FIM logs](https://github.com/Achiefs/fim/assets/96399625/496997e1-e6bf-4301-9675-70a9526bb150)

**Comment by okynos** [comment]
Yes @rpmranjith, The ignore field works as a string match in the file name not as regex. So, you need to remove the `*` from the `ignore: ["*.swp"]` option. Left only `.swp` inside the ignore parameter like `ignore: [".swp"]`. It will match any `.swp` in the file name.

**Comment by rpmranjith** [comment]
Hello @okynos 
Thanks for the reply, it works now, now we are unable to capture the user information who did the creation/modification/deletion, of the auditing file, instead it's shows the auid, while I am comparing the auid in my system audit log it matches my user id... is there any way to capture the user log into FIM logs would be much appreciated for us to getting into implementation please.  

![image](https://github.com/Achiefs/fim/assets/96399625/d1eb182e-2b24-4f9c-9291-dd9f558df0e2)

**Comment by okynos** [comment]
@rpmranjith 
The `auid` field should be in the Splunk or FIM events file. For example, take a look at my previous message the Splunk event contains the `auid` field on it.
![image](https://github.com/Achiefs/fim/assets/10661307/166a2171-4ddd-491a-93fb-41a6d3d9510d)

By the way, FIM only processes events associated with a file. The Audit type `USER_START` doesn't refer to a file.
The screenshot shows the audit log but it is produced by Audit daemon not by FIM.

**Comment by rpmranjith** [comment]
hello @okynos, 
Yes you are correct, above screenshot I showed you in audit log that captured the user information, and same **_auid_** value been captured in FIM events as well, howerver it's not capturing for all the events generated by FIM agent, 
Sample I have attached the SIEM event where it's not capturing the auid information, 
can you please paste here your server config.yml configuration to compare our settings please 

![image](https://github.com/Achiefs/fim/assets/96399625/7cd71fd8-1f56-4077-bc2b-789d00e9a0e0)

**Comment by okynos** [comment]
Hello @rpmranjith,

I see. Your problem is related to the audit configuration inside the `config.yml`. Here you have a default FIM configuration for Linux https://github.com/Achiefs/fim/blob/main/config/linux/config.yml. This configuration contains monitoring methods `Audit` and `monitor`.
The `monitor` block doesn't process Audit daemon data. So, you have to include the paths you want to get Audit information into the audit block.
For example, for the file `/etc/test.conf~`. I recommend something like this:
Original:
```
audit:
  - path: /tmp
    labels: ["tmp", "linux"]
    ignore: [".swp"]

monitor:
  - path: /bin/
  - path: /usr/bin/
    labels: ["usr/bin", "linux"]
  - path: /etc
    labels: ["etc", "linux"]
```

Target configuration:
```
audit:
  - path: /tmp
    labels: ["tmp", "linux"]
    ignore: [".swp"]
  - path: /etc
    labels: ["etc", "linux"]

monitor:
  - path: /bin/
  - path: /usr/bin/
    labels: ["usr/bin", "linux"]
```

**Comment by rpmranjith** [comment]
Hello @okynos 
Thanks for sharing the configuration, i have already configured the same configuration, however it's just capturing the auid information only for deleting the file,  logs are not capturing for both creation & modification

node: "FIM"

# Events configuration, where to store produced events
events:
  destination: file
  file: /var/log/fim/events.json

# Audit extended files and folders information
audit:
  - path: /etc
    labels: ["tmp", "linux"]
    ignore: [".swp"]

# Simple files and folders information
monitor:
  - path: /bin/
  - path: /usr/bin/
    labels: ["usr/bin", "linux"]
  - path: /etc
    labels: ["Critical Linux Configuration", "linux"]

# App procedure and errors logging
log:
  file: /var/log/fim/fim.log
  # Available levels [debug, info, error, warning]
  level: debug

**Comment by rpmranjith** [comment]
Hello @okynos 
Now I have completely tested out the functionalities, requesting you to add below enhancements into your build, 

Need to capture **auid** information with all editors like "nano" "pico" "gnome" "gedit" etc.... 
current it's not capturing the **auid** for commands like cat, it would be really great if it's capturing for this as well.

**Comment by okynos** [comment]
Thanks @rpmranjith, I will include those enhancements as soon as possible.
