### ISSUE TITLE
Include PID and parent process PID in the event information

### ISSUE THREAD

**Issue by alberpilot** [Achiefs/fim#16]
I think that it could be useful to include the process PID (a process that modifies/create/delete a file) and the parent PID. It can be used to correlate more events (like ssh sessions).

**Comment by okynos** [comment]
Hi,

I have done a research about that matter but it seems that notify lacks of such feature on generated raw events
https://docs.rs/notify/4.0.17/notify/struct.RawEvent.html

We will track the issue https://github.com/notify-rs/notify/issues/392 to get some updates, thanks!

**Comment by okynos** [comment]
Added to linux variant in https://github.com/Achiefs/fim/issues/63
