### ISSUE TITLE
Failed to start FIM service

### ISSUE THREAD

**Issue by GambolZou** [Achiefs/fim#169]
I am using windows and installed FIM, however when I try to edit config.yaml file to send event to opensearch, I got following messages:
09:03:06 [INFO] FIM rotator thread started.
09:03:06 [INFO] Events destination selected: BOTH
09:03:06 [INFO] Events file: D:\FIM\events.json
09:03:06 [INFO] Loaded index template from: /etc/fim/index_template.json
09:03:06 [ERROR] thread '<unnamed>' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime': C:\Users\vagrant\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.23.0\src\fs\mod.rs:137
How to solve this issue?
Thanks.

**Comment by okynos** [comment]
Hello @GambolZou 

I will review as soon as possible. Meanwhile, could you share your FIM version and your `config.yml` file? (Remove private tokens please)

**Comment by okynos** [comment]
Hello @GambolZou

I have been doing some research. I solved a problem related to the index template. I'm still working on that but can you confirm this package solves your issue?
Take into account that this is a development package
[fim-0.5.1-1-x64_TEST.zip](https://github.com/user-attachments/files/17335006/fim-0.5.1-1-x64_TEST.zip)
Let me know if it works for you I will prepare the release patch as soon as possible, Thank you for your feedback.

**Comment by GambolZou** [comment]
One more thing, when I add audit section as below, the service can't start:
audit:
  - path: D:\FIM_TEST1
    labels: ["Audit","FIM_TEST1", "WINDOWS"]
  - path: D:\FIM_TEST
    labels: ["Audit","FIM_TEST", "WINDOWS"]
Does that mean audit function won't work in Windows ?
