### ISSUE TITLE
Add whodata information to the events

### ISSUE THREAD

**Issue by okynos** [Achiefs/fim#63]
Hello all!

We have detected a need into our software. We lack of information about who performs a change.
We have to include this feature as soon as possible to increase the value of our product.

Regards!

**Comment by okynos** [comment]
We are working on the best approach to manage whodata information provided by the auditd daemon.
Options:
- Monitor audit log
- Search file events with `ausearch`

**Comment by okynos** [comment]
We will need to include into the development a way to monitor external auditd rules.

**Comment by okynos** [comment]
Development almost finished we will start testing round. We will redact here the expected tests.
- A
- B
- C

**Comment by okynos** [comment]
We will include unit tests to improve coverage report. We need to increase from 48% to nearly 80%

**Comment by alberpilot** [comment]
> Development almost finished we will start testing round. We will redact here the expected tests.
> 
> Create file in audit monitor folder
> Create file in not monitored folder
> Create file in not monitored folder that is in audit rules
> Delete file in monitored folder
> Nano to a file inside monitored folder
> Pipe of a command to a file inside monitored folder
> Loop of create or delete files inside monitored folder
> Chown/Chmod of file inside monitored folder
> Add audit rules in execution time auditctl -w /opt -p wa -k fim

Could hard/symbolic links be taken into account?

**Comment by okynos** [comment]
> Could hard/symbolic links be taken into account?

I have tested symbolic links. Audit detects them but FIM ignore events due to the event format. We will include a modification to support links.

**Comment by okynos** [comment]
> Could hard/symbolic links be taken into account?

Solved here 43b6385 thx!

**Comment by okynos** [comment]
Important information about syscalls by architecture
x86 -> https://github.com/torvalds/linux/blob/master/arch/x86/entry/syscalls/syscall_64.tbl
ARM -> https://github.com/torvalds/linux/blob/master/arch/arm/tools/syscall.tbl
