### ISSUE TITLE
Windows error 1063

### ISSUE THREAD

**Issue by dimforensics** [Achiefs/fim#84]
successefully installed, but the service is stopping.

trying fim.exe from command line.. it gives Error:
Winapi(Os { code: 1063, kind: Uncategorized, message: "The service process could not connect to the service controller." })

**Comment by okynos** [comment]
Thanks for your report, working on it.
Which is your Windows version?

**Comment by okynos** [comment]
Hello @dimforensics,

We have just published a new version to fix this problem. Take a look at our release page v0.4.4 https://github.com/Achiefs/fim/releases/tag/v0.4.4
You will need to install this version and go to the `services.msc` service to start FIM. Let me know if it works as expected.
![image](https://user-images.githubusercontent.com/10661307/218879768-db044598-e6fc-46ca-b04c-e9f57416604d.png)


Thanks for your feedback, and sorry for any inconvenience. Don't hesitate to ask us if you have any doubts.

**Comment by okynos** [comment]
We will close this issue as solved, don't hesitate to reopen if you need, thanks!

**Comment by dimforensics** [comment]
all works!
Thank you very much.
