### ISSUE TITLE
Include buffered reading when calculating hash of a file

### ISSUE THREAD

**Issue by TJOSERAFAEL** [Achiefs/fim#90]
On this line: https://github.com/Achiefs/fim/blob/main/src/hash.rs#L15 it would be great to do a buffered reading to avoid problems with large files.

**Comment by okynos** [comment]
We have done a first research. Testing with 1GB file the following error is throw:
```
17:39:57 [DEBUG] (1) fim::hash: Error not handled: Uncategorized
```

We have to develop a way to manage this cases.
